# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2018

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  # About: /about

# ===========================================
# Theme Settings
# ===========================================
# color: default | mint green | cobalt blue | hot pink | dark violet
color: default

# default page mode: default | archives
mode: default

toc: true

# jQuery fancybox
fancybox: true

pjax: true

copyright:
  enable: false
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: ariaszzzhc@qq.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/Ariaszzzhc
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics:
# Baidu Verification
baidu_verification:

# Google Analytics
google_analytics: UA-115297697-1
# Google Verification
google_verification:

# Disqus
disqus_shortname:

# Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# Gitalk
gitalk:
  enable: true
  githubID: Ariaszzzhc
  repo: hiarias
  ClientID: aeeb8d40e235a733a88b
  ClientSecret: e3bd52ec3fb27c4eaec96efc4be7011ae43d274a
  adminUser: Ariaszzzhc
  distractionFreeMode: true

# ===========================================
# Version
# ===========================================
version: 2.10.1
