# Meta
description: 某非酋的部落格
keywords: hexo,theme,typescript,otakism,otaku
site_desc: salted fish have dreams

# Navigation
navigation:
- name: Home
  slug: home
  url: /
- name: Archives
  slug: archives
  url: /archives

# Search
search: 
  enable: true
  service: google # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Miscellaneous
google_analytics:
favicon: /favicon.png
author_url: http://rakugaki.me

# Less
less:
  compress: true

# use url, not username
social:
- slug: email
  url: mailto:ariaszzzhc@qq.cim
- slug: github
  url: https://github.com/Ariaszzzhc
